GET http://localhost:3000/recursos

###

GET http://localhost:3000/recursos/1

###

POST http://localhost:3000/recursos HTTP/1.1
Content-Type: application/json

    {
        "id_recurso": 2,
        "nombreRe": "Material de oficina",
        "ubicacion": "Calle 2",
        "tipoRecurso": "equipamiento",
        "estadoRecurso": "disponible"
    }

###
PUT http://localhost:3000/recursos/1 HTTP/1.1
Content-Type: application/json

    {
        "id_recurso": 2,
        "nombreRe": "Material de oficina",
        "ubicacion": "Calle 2",
        "tipoRecurso": "equipamiento",
        "estadoRecurso": "disponible"
    }

###
DELETE http://localhost:3000/recursos/2 HTTP/1.1